---
- name: "Restart OpenSSH"
  listen: "restart openssh"
  become: true
  service:
    name: sshd
    state: restarted
- name: "Restart resolvconf"
  listen: "restart resolvconf"
  become: true
  service:
    name: resolvconf
    state: restarted
