---
- name: "Restart OpenSSH"
  listen: "restart openssh"
  become: true
  service:
    name: sshd
    state: restarted
- name: "Restart resolvconf"
  listen: "restart resolvconf"
  become: true
  service:
    name: resolvconf
    state: restarted
- name: "Restart Seafile"
  listen: "restart seafile"
  become: true
  community.general.docker_compose:
    project_src: /opt/seafile-docker-compose
    build: no
    restarted: yes
