---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: xenial32
      box: xenial32
      box_url: https://atlas.hashicorp.com/ubuntu/boxes/xenial32/versions/20170512.0.0/providers/virtualbox.box
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1
  instances:
    - name: env-common
      ansible_groups:
        - group1
verifier:
  name: testinfra
